### ISSUE TITLE
Need GraphQL Implementation

### ISSUE THREAD

**Issue by sulthanmamusa** [kamilmysliwiec/universal-nest#11]
Hi Kamil Myśliwiec,

I am trying @nestjs/ng-universal with GraphQL and I am getting the following error:

**ERROR in ./node_modules/graphql/index.mjs 64:0-70:117
Can't reexport the named export 'visitWithTypeInfo' from non EcmaScript module (only default export is available)
 @ ./node_modules/@nestjs/graphql/dist/graphql.module.js
 @ ./node_modules/@nestjs/graphql/dist/index.js
 @ ./node_modules/@nestjs/graphql/index.js
 @ ./server/app.module.ts
 @ ./server/main.ts**

Note: Please let me know what and where I want to add/modify the configuration for running GraphQL with this module.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by gaurav-bothra** [comment]
facing same issue.
