### ISSUE TITLE
Build failed after nestjs upgraded to 6.0.0

### ISSUE THREAD

**Issue by trendchaser4u** [kamilmysliwiec/universal-nest#13]
After updating nestjs dependencies to 6.0.0 nest-universe build failed. PFA

package.json

![image](https://user-images.githubusercontent.com/8087340/54592650-d43c3500-4a52-11e9-8f62-493d733ba023.png)

Build command:

`npm run build:ssr && npm run serve:ssr`

Error:

![image](https://user-images.githubusercontent.com/8087340/54592876-3d23ad00-4a53-11e9-96f3-934f005c22f6.png)

**Comment by kamilmysliwiec** [comment]
Fixed :) Please, pull updated version.

**Comment by trendchaser4u** [comment]
@kamilmysliwiec Thanks for the quick fix. could you please share the fix's commit id.

**Comment by kamilmysliwiec** [comment]
Well, simply update `@nestjs/ng-universal` :) It should be enough
