### ISSUE TITLE
Update readme for prerender step

### ISSUE THREAD

**Issue by mohammedzamakhan** [kamilmysliwiec/universal-nest#15]
The command for pre render works fine
```
npm run build:prerender && npm run serve:prerender
```

But I think the nextjs server should be running before we run this command so that the API can be accessed while prerendering.

Can you update the readme about this.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? :)

**Comment by kamilmysliwiec** [comment]
Prerendering is now shipped by Angular team as part of the official Universal package.  Simply run `npm run prerender` to prerender your application. If you face any issue, please, report this in the official repository https://github.com/angular/universal
