### ISSUE TITLE
Configure webconfig file

### ISSUE THREAD

**Issue by marcocoelho** [kamilmysliwiec/universal-nest#19]
Hello guys.
I need help.

I was using @ ng-toolkit / universal. Where does it have a local.js file

I removed him from my project and I'm working with Nest. I did all the build part for production and arresting.
I applied the files generated in dist on the server.

With the toolkit that had a webconfig, pointing the path of the local.js file that read the dist / server folder.

With Nest I found the file server-scripts.js. Putting it on my server and pointing the way the project does not open.

Is there any other webconfig setup to be done? The server is windows.

**Comment by kamilmysliwiec** [comment]
Please, use NestJS [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. I'm using GitHub to track bugs, feature requests, and potential improvements.
