### ISSUE TITLE
POST request in app.controller

### ISSUE THREAD

**Issue by gp187** [kamilmysliwiec/universal-nest#22]
I'm trying to access this route via a http call and store in `app.controller` 
No matter what I do, the path isn't found. 

Is there any way to this?

```
  /**
   * Get an email from the coming soon or newsletter
   */
  @Post('send/message/email')
  public sendMessageEmail(
    @Body() body
  ) {
    console.warn(`body > `, body);
     return body;
  }
```

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
