### ISSUE TITLE
Can't resolve 'project/src' in 'project/dist/server'

### ISSUE THREAD

**Issue by kenobi-io** [kamilmysliwiec/universal-nest#29]
after mirgate project to nx(nrwl)

$ yarn run build:ssr
...
> webpack --config webpack.server.config.js --progress --colors
ERROR in ./dist/server/main.js
Module not found: Error: Can't resolve 'project/src' in 'project/dist/server'
 @ ./dist/server/main.js 45:24-159
 @ ./prerender.ts

ERROR in ./node_modules/@angular/core/fesm5/core.js
Module not found: Error: Can't resolve 'project/src' in 'project/node_modules/@angular/core/fesm5'
 @ ./node_modules/@angular/core/fesm5/core.js 27838:15-36 27850:15-102
 @ ./prerender.ts

ERROR in ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'project/src' in 'project/node_modules/express/lib'
 @ ./node_modules/express/lib/view.js 81:13-25
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./node_modules/@nestjs/ng-universal/dist/utils/setup-universal.utils.js
 @ ./node_modules/@nestjs/ng-universal/dist/angular-universal.providers.js
 @ ./node_modules/@nestjs/ng-universal/dist/angular-universal.module.js
 @ ./node_modules/@nestjs/ng-universal/dist/index.js
 @ ./node_modules/@nestjs/ng-universal/index.js
 @ ./prerender.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! client@0.1.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the client@0.1.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     npm/_logs/2019-09-27T09_00_54_247Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kamilmysliwiec** [comment]
This package is not compatible with Nx
