### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED livereload.js:1

### ISSUE THREAD

**Issue by matenoz** [kamilmysliwiec/universal-nest#30]
Hi,
With Server-Side Rendering(ssr) in dev-tools console the following error appears

> Failed to load resource: net::ERR_CONNECTION_REFUSED  livereload.js:1

It seems it can't find livereload.js

I've tried to install and configure webpack-livereload-plugin but doesn't work.

Any suggestionts?
Thank you

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by cfremgen** [comment]
> Please, provide a minimal repository which reproduces your issue.

Here you go: https://github.com/kamilmysliwiec/universal-nest

**Comment by cieldon32** [comment]
I get the same problem.

**Comment by KingDarBoja** [comment]
This is caused by either the `serve-script.js` file, where `LiveReloadCompiler` is being called or `liveReload: true` at `server/app.module.ts`.

Setting the flag to **false** will get rid of the dev-tools error.

**Comment by kamilmysliwiec** [comment]
`LiveReloadCompiler` has been removed in the latest version
