### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by emertola** [kamilmysliwiec/universal-nest#31]
I tried to run the npm run build:ssr && npm run serve:ssr, and it returned an error:

```
/<project_path>/node_modules/pdfjs-dist/build/pdf.js:1057
    if (typeof Element.prototype.remove !== 'undefined') {

ReferenceError: Element is not defined
```
Note, that this is an existing angular app and I just added angular universal using nestjs approach.
What I did was converted angular 7 to 8, then added angular universal.

Please help.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.
