### ISSUE TITLE
generated dist server.js needs node_modules

### ISSUE THREAD

**Issue by jakubjosef** [kamilmysliwiec/universal-nest#32]
Hi,
when I used ng-universal in my project and generated output in /dist folder I found this output requires node_modules presence. Is that correct or I'm doing something wrong?

AFAIK dist folder should be independent and used for prod build. 

Is this is correct behaviour of universal-nest, please close this issue.

Thank you.
Jakub Josef

**Comment by kamilmysliwiec** [comment]
Some `node_modules` packages are required.

**Comment by jakubjosef** [comment]
Okay thank you. That not sounds logically for me, but at least I know it's desired state.

We have a nestJS backend for our Angular app and we wanted to have SSR and this solution looked promising. 

Unfortunately we have some problems with implementation, if you'll have some time I would ask few questions to you.

1) What's the difference between server.js and dist/server. I don't understand why we building it, it looks like main.js from dist/server is not used at all, it returning empty output if runned etc.

2) Can we skip creating one file and use dist/server with all files? We need to have multifile bundle to  be able to change some configuration files using k8s volumes.

Sorry for sending support request here, however it will be very helpful for us if you find some time to answer.

Thanks in advance.
Jakub Josef
