### ISSUE TITLE
Issue running npm start or ng serve

### ISSUE THREAD

**Issue by lightzumo** [kamilmysliwiec/universal-nest#36]
Hello, I just downloaded your rep and when I start the app with either npm start or ng serve (after obviously npm i) when I go to the speakers tabl I don't see anything and there is an error in the console: "Failed to load resource: the server responded with a status of 404 (Not Found)" and "HttpErrorResponse
defaultErrorLogger @ core.js:5828". 
When I run you server side rendering command everything works fine. Maybe I did something wrong because I new to Universal and to NestJS.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by lightzumo** [comment]
Well, I have Angular 8.3.25 installed, and as I said, I just downloaded your example and followed your steps.

**Comment by kamilmysliwiec** [comment]
With `npm run start` (`ng serve`) your API isn't running. Hence, you won't see anything in the speakers table.
