### ISSUE TITLE
How can i make my nesjs angular ssr to render a particular page based on POST request to my nestjs app

### ISSUE THREAD

**Issue by abbasogaji** [kamilmysliwiec/universal-nest#38]
Hey guys i need help with this flow,

So am working on an application that requires me to render a page once i send a POST request.

 I am able to achieve with basic Nestjs MVC from my controller as usual 

```typescript

@Post()
@Render('index')
respondToPayRequest(@Body bd){
  return bd;
}

```
but am looking for a way to achieve this using

Nestjs + Angular universal (SSR)

So once a user submits a form like this 

<form action="URL_TO_MY_ANGULAR_UNIVERSAL_ROUTE"  method="POST">

From a different website to mine

My Nestjs should respond to the POST request and render a page from Angular UNIVERSAL

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
