### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by weeco** [kamilmysliwiec/universal-nest#4]
Hey Kamil,
do you have any documentation for the universal nest module available beside the Readme and this code? What do I need to add, so that I can serve my existing Angular application with server side rendering using nest?

**Comment by weeco** [comment]
I got my own application running with Nest-universal. Most important to note is that one has to follow the Angular universal tutorial I guess.

**Comment by natejgardner** [comment]
Looks like out of the box, ng-cli is a bit confused about project names. Could you document the proper syntax for generating an Angular component using ng-cli in this boilerplate project? I.e., which project name will generate components in src?

**Comment by marcus-sa** [comment]
What about the `bootstrap` option there is in `ngExpressEngine`? Seems like there's no support for that, or does it just lack documentation in `@nestjs/ng-universal`? hmm

**Comment by kamilmysliwiec** [comment]
Hey @weeco,
I would suggest creating an issue in the docs repo instead (it's just an example repository :))
